fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_member:
    resource: '@AppBundle/Controller/MemberController.php'
    type: annotation

app_website:
    resource: '@AppBundle/Controller/HomepageController.php'
    type: annotation